[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "StoreReceiptAnalyzer"
version = "1.0.0"
description = "StoreReceiptAnalyzer is a self-hosted, local AI-powered platform that transforms shopping receipts into structured expense data while keeping your financial information private and fully under your control."
requires-python = ">=3.10"

[project.scripts]
as-worker = "analizzascontrini.cli:run_worker"
as-webui = "analizzascontrini.cli:run_webui"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"analizzascontrini.webui.spese" = [
    "templates/**/*.html",
    "static/**/*",
]

"analizzascontrini.webui" = [
    "locale/**/*.mo",
]