# Generated by Django 6.0.7 on 2026-07-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scontrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('data_scontrino', models.DateField(blank=True, null=True)),
                ('nome_negozio_ocr', models.CharField(blank=True, max_length=255, null=True)),
                ('immagine', models.ImageField(upload_to='scontrini/')),
                ('totale', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('confermato', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupermercatoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('parola_chiave', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spese.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAnalisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_task', models.CharField(choices=[('OCR_ESTRAZIONE', 'Task 1: OCR e Lettura Grezza'), ('CATEGORIZZAZIONE', 'Task 2: Assegnazione Categorie via LLM')], max_length=30)),
                ('stato', models.CharField(choices=[('PENDING', 'In attesa'), ('PROCESSING', 'In elaborazione'), ('COMPLETED', 'Completato'), ('FAILED', 'Fallito')], default='PENDING', max_length=20)),
                ('errore', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('scontrino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='spese.scontrino')),
            ],
        ),
        migrations.CreateModel(
            name='VoceScontrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringa_originale', models.CharField(max_length=255)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('articolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spese.articolo')),
                ('scontrino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='spese.scontrino')),
            ],
        ),
        migrations.CreateModel(
            name='DizionarioArticolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringa_scontrino', models.CharField(max_length=255)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spese.articolo')),
                ('supermercato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dizionario', to='spese.supermercatotemplate')),
            ],
            options={
                'unique_together': {('supermercato', 'stringa_scontrino')},
            },
        ),
    ]
