# Generated by Django 6.0.7 on 2026-07-09 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scontrino',
            name='supermercato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spese.supermercatotemplate'),
        ),
    ]
