# Generated by Django 6.0.7 on 2026-07-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0002_scontrino_supermercato'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermercatotemplate',
            name='parsing_hint',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vocescontrino',
            name='prezzo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vocescontrino',
            name='quantita',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
