# Generated by Django 6.0.7 on 2026-07-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0003_supermercatotemplate_parsing_hint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermercatotemplate',
            name='parsing_hint',
        ),
        migrations.AddField(
            model_name='supermercatotemplate',
            name='prompt_instruction',
            field=models.TextField(blank=True, help_text='Regole specifiche da iniettare nel prompt', null=True),
        ),
        migrations.AddField(
            model_name='supermercatotemplate',
            name='regex_quantita',
            field=models.CharField(blank=True, help_text='Regex per estrarre qtà', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supermercatotemplate',
            name='regex_sconto',
            field=models.CharField(blank=True, help_text='Regex per estrarre sconti', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supermercatotemplate',
            name='separatore_blocco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
