# Generated by Django 6.0.7 on 2026-07-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0004_remove_supermercatotemplate_parsing_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocescontrino',
            name='sconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
