# Generated by Django 6.0.7 on 2026-07-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0005_vocescontrino_sconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermercatotemplate',
            name='articoli_ripetuti',
            field=models.BooleanField(default=False),
        ),
    ]
