# Generated by Django 6.0.7 on 2026-07-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0006_supermercatotemplate_articoli_ripetuti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermercatotemplate',
            name='regex_sconto',
        ),
        migrations.RemoveField(
            model_name='supermercatotemplate',
            name='separatore_blocco',
        ),
        migrations.AddField(
            model_name='supermercatotemplate',
            name='prompt_instruction_sconti',
            field=models.TextField(blank=True, help_text="Regole specifiche per estrarre sconti (es. 'cerca Taglio Prezzo sotto articoli con *')", null=True),
        ),
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='articoli_ripetuti',
            field=models.BooleanField(default=False, help_text='Se True, il negozio può avere lo stesso articolo più volte'),
        ),
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='parola_chiave',
            field=models.CharField(help_text='Parola per identificare il negozio', max_length=100),
        ),
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='prompt_instruction',
            field=models.TextField(blank=True, help_text="Regole specifiche per estrarre articoli (es. 'ignora VI*', 'articoli con asterisco hanno prezzo pieno')", null=True),
        ),
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='regex_quantita',
            field=models.CharField(blank=True, help_text="Regex per estrarre quantità (es. r'^(\\d+)\\s*PZ\\s*x\\s*E\\.?\\s*([\\d,]+)$')", max_length=255, null=True),
        ),
    ]
