# Generated by Django 6.0.7 on 2026-07-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0007_remove_supermercatotemplate_regex_sconto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='regex_quantita',
            field=models.CharField(blank=True, help_text='Regex per estrarre quantità', max_length=255, null=True),
        ),
    ]
