# Generated by Django 6.0.7 on 2026-07-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0008_alter_supermercatotemplate_regex_quantita'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermercatotemplate',
            name='righe_da_ignorare',
            field=models.JSONField(blank=True, default=list, help_text="Lista pattern da saltare durante il parsing del nome articolo (es. ['VI*', 'Taglio Prezzo'])"),
        ),
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='articoli_ripetuti',
            field=models.BooleanField(default=False, help_text='Se True, il negozio può avere lo stesso articolo più volte (es. BANCO SALUMI)'),
        ),
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='parola_chiave',
            field=models.CharField(help_text="Parola per identificare il negozio dall'OCR (es. 'DUEPI', 'CONAD', 'COOP')", max_length=100),
        ),
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='prompt_instruction',
            field=models.TextField(blank=True, help_text="Regole specifiche per estrarre articoli (es. 'articoli con asterisco hanno prezzo pieno', 'ignora righe Kg x E.')", null=True),
        ),
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='prompt_instruction_sconti',
            field=models.TextField(blank=True, help_text="Regole specifiche per estrarre sconti (es. 'cerca Taglio Prezzo sotto articoli con *', 'sconto positivo')", null=True),
        ),
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='regex_quantita',
            field=models.CharField(blank=True, help_text="Regex per estrarre quantità (es. r'^(\\d+)\\s*PZ\\s*x\\s*E\\.?\\s*([\\d,]+)$')", max_length=255, null=True),
        ),
    ]
