# Generated by Django 6.0.7 on 2026-07-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0009_supermercatotemplate_righe_da_ignorare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanalisi',
            name='percentuale',
            field=models.IntegerField(default=0),
        ),
    ]
