# Generated by Django 6.0.7 on 2026-07-18 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0010_taskanalisi_percentuale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dizionarioarticolo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dizionari', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scontrino',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scontrini', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supermercatotemplate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supermercati_template', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskanalisi',
            name='datas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taskanalisi',
            name='step',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taskanalisi',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_analisi', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ScontrinoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='test/')),
                ('nome_negozio_ocr', models.CharField(blank=True, max_length=255, null=True)),
                ('data_scontrino', models.DateField(blank=True, null=True)),
                ('totale', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supermercato_testato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='spese.supermercatotemplate')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_scontrino', to='spese.taskanalisi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scontrini_test', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scontrini Test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoceScontrinoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringa_originale', models.CharField(max_length=255)),
                ('quantita', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('prezzo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('articolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voci_test', to='spese.articolo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voci_test', to='spese.categoria')),
                ('scontrino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='spese.scontrinotest')),
            ],
        ),
    ]
