# Generated by Django 6.0.7 on 2026-07-18 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0011_articolo_user_categoria_user_dizionarioarticolo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanalisi',
            name='scontrino_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='spese.scontrinotest'),
        ),
        migrations.AlterField(
            model_name='taskanalisi',
            name='scontrino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='spese.scontrino'),
        ),
    ]
