# Generated by Django 6.0.7 on 2026-07-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0012_taskanalisi_scontrino_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermercatotemplate',
            name='prompt_instruction_sconti',
        ),
        migrations.AddField(
            model_name='supermercatotemplate',
            name='parole_chiave_negozio',
            field=models.JSONField(blank=True, default=list, help_text='Lista parole chiave per identificare il nome negozio (es. ["duepi", "ipercoop"])'),
        ),
        migrations.AddField(
            model_name='supermercatotemplate',
            name='pattern_rimuovi_iva',
            field=models.CharField(blank=True, help_text="Regex per rimuovere IVA/VI* (es. '\\s+VI\\*' o '\\s+\\d+%')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supermercatotemplate',
            name='regex_sconti',
            field=models.CharField(blank=True, help_text="Regex per identificare le righe di sconto (es. 'Taglio Prezzo|SCONTO OFFERTA')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='regex_quantita',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='righe_da_ignorare',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='taskanalisi',
            name='tipo_task',
            field=models.CharField(choices=[('OCR_ESTRAZIONE', 'Task 1: OCR e Lettura Grezza'), ('CATEGORIZZAZIONE', 'Task 2: Assegnazione Categorie via LLM'), ('TEST_SUPERMERCATO', 'Task test template del supermercato')], max_length=30),
        ),
    ]
