# Generated by Django 6.0.7 on 2026-07-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0013_remove_supermercatotemplate_prompt_instruction_sconti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanalisi',
            name='confermato',
            field=models.BooleanField(default=False, help_text="True se il test è stato confermato dall'utente"),
        ),
        migrations.AlterField(
            model_name='supermercatotemplate',
            name='prompt_instruction',
            field=models.TextField(blank=True, help_text='Regole specifiche per estrarre articoli dello scontrino specifico', null=True),
        ),
    ]
