# Generated by Django 6.0.7 on 2026-07-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0014_taskanalisi_confermato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanalisi',
            name='stato',
            field=models.CharField(choices=[('PENDING', 'In attesa'), ('PROCESSING', 'In elaborazione'), ('COMPLETED', 'Completato'), ('FAILED', 'Fallito')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskanalisi',
            name='step',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskanalisi',
            name='tipo_task',
            field=models.CharField(choices=[('OCR_ESTRAZIONE', 'Task 1: OCR e Lettura Grezza'), ('CATEGORIZZAZIONE', 'Task 2: Assegnazione Categorie via LLM'), ('TEST_SUPERMERCATO', 'Task test template del supermercato')], max_length=50),
        ),
    ]
