# Generated by Django 6.0.7 on 2026-07-23 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0015_alter_taskanalisi_stato_alter_taskanalisi_step_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanalisi',
            name='tipo_task',
            field=models.CharField(choices=[('OCR_ESTRAZIONE', 'Task 1: OCR e Lettura Grezza'), ('CATEGORIZZAZIONE', 'Task 2: Assegnazione Categorie via LLM'), ('TEST_SUPERMERCATO', 'Task test template del supermercato'), ('OLLAMA_CHECK', 'Verifica connessione Ollama e modelli')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ollama_host', models.CharField(blank=True, default='', help_text='URL di Ollama (es: http://192.168.1.45:11434). Lascia vuoto per usare il default di sistema.', max_length=200)),
                ('modello_ocr', models.CharField(blank=True, default='', max_length=100)),
                ('modello_analisi', models.CharField(blank=True, default='', max_length=100)),
                ('modello_categorizzazione', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_ocr', models.TextField(blank=True, default='')),
                ('prompt_analisi', models.TextField(blank=True, default='')),
                ('prompt_categorizzazione', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurazione AI Utente',
                'verbose_name_plural': 'Configurazioni AI Utenti',
            },
        ),
    ]
