# Generated by Django 6.0.7 on 2026-07-24 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0016_alter_taskanalisi_tipo_task_useraiconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('user', 'nome'), name='unique_user_categoria'),
        ),
    ]
