# Generated by Django 6.0.7 on 2026-07-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0017_categoria_unique_user_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
