# Generated by Django 6.0.7 on 2026-07-24 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0018_alter_categoria_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'verbose_name': 'Articolo', 'verbose_name_plural': 'Articoli'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='dizionarioarticolo',
            options={'verbose_name': 'Dizionario Articolo', 'verbose_name_plural': 'Dizionari Articolo'},
        ),
        migrations.AlterModelOptions(
            name='scontrino',
            options={'verbose_name': 'Scontrino', 'verbose_name_plural': 'Scontrini'},
        ),
        migrations.AlterModelOptions(
            name='scontrinotest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Scontrino Test', 'verbose_name_plural': 'Scontrini Test'},
        ),
        migrations.AlterModelOptions(
            name='supermercatotemplate',
            options={'verbose_name': 'SupermercatoTemplate', 'verbose_name_plural': 'SupermercatiTemplate'},
        ),
        migrations.AlterModelOptions(
            name='taskanalisi',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='vocescontrino',
            options={'verbose_name': 'VoceScontrino', 'verbose_name_plural': 'VociScontrino'},
        ),
        migrations.AlterModelOptions(
            name='vocescontrinotest',
            options={'verbose_name': 'Voce Scontrino Test', 'verbose_name_plural': 'Voci Scontrino Test'},
        ),
        migrations.AlterUniqueTogether(
            name='dizionarioarticolo',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dizionarioarticolo',
            constraint=models.UniqueConstraint(fields=('user', 'supermercato', 'stringa_scontrino'), name='unique_user_supermercato_scontrino'),
        ),
    ]
