# Generated by Django 6.0.7 on 2026-07-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0020_alter_taskanalisi_tipo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanalisi',
            name='tipo_task',
            field=models.CharField(choices=[('OCR_ESTRAZIONE', 'Task 1: OCR e Lettura Grezza'), ('CATEGORIZZAZIONE', 'Task 2: Assegnazione Categorie via LLM'), ('TEST_SUPERMERCATO', 'Task test template del supermercato'), ('OLLAMA_CHECK', 'Verifica connessione Ollama e modelli'), ('CHAT', 'Chat assistente'), ('OCR_ONLY', 'OCR semplice')], max_length=50),
        ),
    ]
