# Generated by Django 6.0.7 on 2026-07-26 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0021_alter_taskanalisi_tipo_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Optional description explaining what belongs to this category', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_text', models.CharField(max_length=255, verbose_name='Receipt text')),
            ],
            options={
                'verbose_name': 'Product dictionary entry',
                'verbose_name_plural': 'Product dictionary entries',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='Receipt date')),
                ('ocr_store_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Store name from OCR')),
                ('image', models.ImageField(upload_to='receipts/', verbose_name='Image')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(max_length=255, verbose_name='Original receipt text')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Unit price')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Receipt item',
                'verbose_name_plural': 'Receipt items',
            },
        ),
        migrations.CreateModel(
            name='ReceiptTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tests/')),
                ('ocr_store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Receipt test',
                'verbose_name_plural': 'Receipt tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptTestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Receipt test item',
                'verbose_name_plural': 'Receipt test items',
            },
        ),
        migrations.CreateModel(
            name='StoreTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('keyword', models.CharField(help_text="Keyword used to identify the store from OCR (e.g. 'DUEPI', 'CONAD', 'COOP')", max_length=100, verbose_name='Keyword')),
                ('prompt_instruction', models.TextField(blank=True, help_text='Specific rules for extracting receipt items for this store', null=True, verbose_name='Prompt instructions')),
                ('quantity_regex', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quantity regex')),
                ('ignored_lines', models.JSONField(blank=True, default=list, verbose_name='Ignored lines')),
                ('discount_regex', models.CharField(blank=True, help_text="Regex used to identify discount lines (e.g. 'Taglio Prezzo|SCONTO OFFERTA')", max_length=200, null=True, verbose_name='Discount regex')),
                ('remove_vat_pattern', models.CharField(blank=True, help_text="Regex used to remove VAT markers (e.g. '\\s+VI\\*' or '\\s+\\d+%')", max_length=100, null=True, verbose_name='VAT removal pattern')),
                ('store_keywords', models.JSONField(blank=True, default=list, help_text="List of keywords used to identify the store name (e.g. ['duepi', 'ipercoop'])", verbose_name='Store keywords')),
                ('repeated_items', models.BooleanField(default=False, help_text='If enabled, the store may have the same item multiple times (e.g. deli counter items)', verbose_name='Repeated items')),
            ],
            options={
                'verbose_name': 'Store template',
                'verbose_name_plural': 'Store templates',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('OCR_EXTRACTION', 'OCR and raw text extraction'), ('CATEGORIZATION', 'LLM category assignment'), ('STORE_TEMPLATE_TEST', 'Store template test'), ('OLLAMA_CHECK', 'Ollama connection and model check'), ('CHAT', 'Assistant chat')], max_length=50, verbose_name='Task type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=100, verbose_name='Status')),
                ('step', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current step')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Error')),
                ('progress', models.IntegerField(default=0, verbose_name='Progress')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Debug logs, results and other task-related data', verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('confirmed', models.BooleanField(default=False, help_text='True if the task result has been confirmed by the user', verbose_name='Confirmed')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.RemoveField(
            model_name='articolo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='articolo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vocescontrino',
            name='articolo',
        ),
        migrations.RemoveField(
            model_name='vocescontrinotest',
            name='articolo',
        ),
        migrations.RemoveConstraint(
            model_name='categoria',
            name='unique_user_categoria',
        ),
        migrations.RemoveField(
            model_name='vocescontrinotest',
            name='categoria',
        ),
        migrations.RemoveConstraint(
            model_name='dizionarioarticolo',
            name='unique_user_supermercato_scontrino',
        ),
        migrations.RemoveField(
            model_name='taskanalisi',
            name='scontrino',
        ),
        migrations.RemoveField(
            model_name='vocescontrino',
            name='scontrino',
        ),
        migrations.RemoveField(
            model_name='scontrinotest',
            name='supermercato_testato',
        ),
        migrations.RemoveField(
            model_name='scontrinotest',
            name='task',
        ),
        migrations.RemoveField(
            model_name='scontrinotest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskanalisi',
            name='scontrino_test',
        ),
        migrations.RemoveField(
            model_name='vocescontrinotest',
            name='scontrino',
        ),
        migrations.RemoveField(
            model_name='supermercatotemplate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskanalisi',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='useraiconfig',
            options={'verbose_name': 'User AI configuration', 'verbose_name_plural': 'User AI configurations'},
        ),
        migrations.RenameField(
            model_name='useraiconfig',
            old_name='modello_analisi',
            new_name='analysis_model',
        ),
        migrations.RenameField(
            model_name='useraiconfig',
            old_name='prompt_analisi',
            new_name='analysis_prompt',
        ),
        migrations.RenameField(
            model_name='useraiconfig',
            old_name='modello_categorizzazione',
            new_name='categorization_model',
        ),
        migrations.RenameField(
            model_name='useraiconfig',
            old_name='prompt_categorizzazione',
            new_name='categorization_prompt',
        ),
        migrations.RenameField(
            model_name='useraiconfig',
            old_name='modello_ocr',
            new_name='ocr_model',
        ),
        migrations.RenameField(
            model_name='useraiconfig',
            old_name='prompt_ocr',
            new_name='ocr_prompt',
        ),
        migrations.AddField(
            model_name='useraiconfig',
            name='chat_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraiconfig',
            name='ollama_host',
            field=models.CharField(blank=True, default='', help_text='Ollama URL (e.g. http://192.168.1.45:11434). Leave empty to use the system default.', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spese.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productdictionary',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spese.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productdictionary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dictionaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spese.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spese.receipt'),
        ),
        migrations.AddField(
            model_name='receipttest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipttestitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_receipt_items', to='spese.category'),
        ),
        migrations.AddField(
            model_name='receipttestitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_receipt_items', to='spese.product'),
        ),
        migrations.AddField(
            model_name='receipttestitem',
            name='receipt_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spese.receipttest'),
        ),
        migrations.AddField(
            model_name='storetemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipttest',
            name='tested_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='spese.storetemplate'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spese.storetemplate', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='productdictionary',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dictionary', to='spese.storetemplate', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='task',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='spese.receipt'),
        ),
        migrations.AddField(
            model_name='task',
            name='receipt_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='spese.receipttest'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipttest',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_tests', to='spese.task'),
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dizionarioarticolo',
            name='articolo',
        ),
        migrations.RemoveField(
            model_name='dizionarioarticolo',
            name='supermercato',
        ),
        migrations.RemoveField(
            model_name='dizionarioarticolo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Scontrino',
        ),
        migrations.DeleteModel(
            name='VoceScontrino',
        ),
        migrations.DeleteModel(
            name='ScontrinoTest',
        ),
        migrations.DeleteModel(
            name='VoceScontrinoTest',
        ),
        migrations.DeleteModel(
            name='TaskAnalisi',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_category'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_product_name'),
        ),
        migrations.AddConstraint(
            model_name='productdictionary',
            constraint=models.UniqueConstraint(fields=('user', 'store', 'receipt_text'), name='unique_user_store_receipt_text'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Articolo',
        ),
        migrations.DeleteModel(
            name='SupermercatoTemplate',
        ),
        migrations.DeleteModel(
            name='DizionarioArticolo',
        ),
    ]
