# Generated by Django 6.0.7 on 2026-07-27 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0022_category_product_productdictionary_receipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='storetemplate',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_store_name'),
        ),
    ]
