# Generated by Django 6.0.7 on 2026-07-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0023_alter_storetemplate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
