# Generated by Django 6.0.7 on 2026-07-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0024_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('update_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Version Check',
                'verbose_name_plural': 'Version Checks',
            },
        ),
    ]
